In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [3]:
X_train = np.array(pd.read_csv('X_train.csv'))
X_test = np.array(pd.read_csv('X_test.csv'))
Y_train = np.array(pd.read_csv('Y_train.csv'))
Y_test = np.array(pd.read_csv('Y_test.csv'))

In [4]:
# Create a logistic regression model
model = LogisticRegression()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print(accuracy)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)



0.8162684869169511
[[1176  136]
 [ 187  259]]


c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
# Create a decision tree model
param_grid = {'max_depth': np.arange(3, 10), 'criterion': ['gini', 'entropy'], 'splitter': ['best', 'random'], 'min_samples_split': np.arange(2, 10), 'min_samples_leaf': np.arange(1, 10)}
model = tree.DecisionTreeClassifier()
grid = GridSearchCV(model, param_grid, scoring='accuracy')
grid.fit(X_train, Y_train)
Y_pred = grid.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print(accuracy)
print(confusion_matrix(Y_test, Y_pred))
print(grid.best_params_)

0.7986348122866894
[[1135  177]
 [ 177  269]]
{'criterion': 'entropy', 'max_depth': 6, 'min_samples_leaf': 1, 'min_samples_split': 3, 'splitter': 'random'}


In [7]:
#create a random forest model
param_grid = {'n_estimators': [10,50,100], 'max_features': ['auto', 'sqrt']}
model = RandomForestClassifier()
grid = GridSearchCV(model, param_grid, scoring='accuracy')
grid.fit(X_train, Y_train)
Y_pred = grid.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print(accuracy)
print(confusion_matrix(Y_test, Y_pred))
print(grid.best_params_)

c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for

0.7918088737201365
[[1167  145]
 [ 221  225]]
{'max_features': 'sqrt', 'n_estimators': 100}


In [13]:
#create a gradient boosting model
param_grid = {'n_estimators': [10,50,100], 'learning_rate': [0.01,0.1,1], 'max_depth': np.arange(3, 10)}
model = GradientBoostingClassifier()
grid = GridSearchCV(model, param_grid, scoring='accuracy')
grid.fit(X_train, Y_train)
Y_pred = grid.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print(accuracy)
print(confusion_matrix(Y_test, Y_pred))

c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Nolan\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

0.8139931740614335
[[1190  122]
 [ 205  241]]


In [14]:
print(grid.best_params_)

{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50}
